name: C/C++ CI

on:
  pull_request:
    branches: main

jobs:
  Checks_changing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cd work dir
      run: cd $(python3 setup_work_dir.py -n ${{ github.event.pull_request.user.login }})
    - name: Build with make
      run: make
    - name: Run tests
      run: make test
        


